In [4]:
from IPython.core.interactiveshell import InteractiveShell
InteractiveShell.ast_node_interactivity = "all"

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

## Agenda

- Why should you use a Pipeline?
- How do you encode categorical features with OneHotEncoder?
- How do you apply OneHotEncoder to selected columns with ColumnTransformer?
- How do you build and cross-validate a Pipeline?
- How do you make predictions on new data using a Pipeline?
- Why should you use scikit-learn (rather than pandas) for preprocessing?

## Step 1: Load the dataset

In [12]:
path_0 = "Scikit_Learn\\data\\titanic_train.csv"
df = pd.read_csv(path_0)

In [13]:
df.shape

(891, 12)

## Step 2: Select features

In [14]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [15]:
df.isna().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
df = df.loc[df["Embarked"].notna(), ['Survived', 'Pclass', 'Sex', 'Embarked']]

In [24]:
df.shape

(889, 4)

In [25]:
df

Survived  Pclass     Sex Embarked
0           0       3    male        S
1           1       1  female        C
2           1       3  female        S
3           1       1  female        S
4           0       3    male        S
..        ...     ...     ...      ...
886         0       2    male        S
887         1       1  female        S
888         0       3  female        S
889         1       1    male        C
890         0       3    male        Q

[889 rows x 4 columns]

In [26]:
df.isna().sum()

Survived    0
Pclass      0
Sex         0
Embarked    0
dtype: int64

In [27]:
df.head()

Survived  Pclass     Sex Embarked
0         0       3    male        S
1         1       1  female        C
2         1       3  female        S
3         1       1  female        S
4         0       3    male        S

## Step 3: Cross-validate a model with one feature

In [28]:
X = df.loc[:, ['Pclass']]
y = df.Survived

In [29]:
print(X.shape)
print(y.shape)

(889, 1)
(889,)


In [32]:
X
y

Pclass
0         3
1         1
2         3
3         1
4         3
..      ...
886       2
887       1
888       3
889       1
890       3

[889 rows x 1 columns]

0      0
1      1
2      1
3      1
4      0
      ..
886    0
887    1
888    0
889    1
890    0
Name: Survived, Length: 889, dtype: int64

In [33]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression(solver='lbfgs')

In [34]:
from sklearn.model_selection import cross_val_score
cross_val_score( logreg, X, y, cv = 5, scoring='accuracy').mean()

0.6783406335301212

In [26]:
y.value_counts()
y.value_counts(normalize=True)

0    549
1    340
Name: Survived, dtype: int64

0    0.617548
1    0.382452
Name: Survived, dtype: float64

## Step 4: Encode categorical features

In [33]:
df.head()

Survived  Pclass     Sex Embarked
0         0       3    male        S
1         1       1  female        C
2         1       3  female        S
3         1       1  female        S
4         0       3    male        S

In [34]:
# dummy encoding of categorical features
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(sparse=False)

In [35]:
ohe.fit_transform(df[['Sex']])

array([[0., 1.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [0., 1.],
       [0., 1.]])

In [36]:
ohe.categories_

[array(['female', 'male'], dtype=object)]

In [37]:
ohe.fit_transform(df[['Embarked']])

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       ...,
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [38]:
ohe.categories_

[array(['C', 'Q', 'S'], dtype=object)]

In [39]:
ohe.fit_transform(df[['Sex', 'Embarked']])

array([[0., 1., 0., 0., 1.],
       [1., 0., 1., 0., 0.],
       [1., 0., 0., 0., 1.],
       ...,
       [1., 0., 0., 0., 1.],
       [0., 1., 1., 0., 0.],
       [0., 1., 0., 1., 0.]])

In [40]:
ohe.categories_

[array(['female', 'male'], dtype=object), array(['C', 'Q', 'S'], dtype=object)]

## Step 5: Cross-validate a Pipeline with all features

In [44]:
X = df.drop('Survived', axis='columns')

In [45]:
X.head()

Pclass     Sex Embarked
0       3    male        S
1       1  female        C
2       3  female        S
3       1  female        S
4       3    male        S

In [46]:
# use when different features need different preprocessing
from sklearn.compose import make_column_transformer

In [47]:
column_trans = make_column_transformer(
    (OneHotEncoder(), ['Sex', 'Embarked']),
    remainder='passthrough')

In [49]:
column_trans.fit_transform(X)

array([[0., 1., 0., 0., 1., 3.],
       [1., 0., 1., 0., 0., 1.],
       [1., 0., 0., 0., 1., 3.],
       ...,
       [1., 0., 0., 0., 1., 3.],
       [0., 1., 1., 0., 0., 1.],
       [0., 1., 0., 1., 0., 3.]])

In [53]:
# chain sequential steps together
from sklearn.pipeline import make_pipeline

In [54]:
pipe = make_pipeline(column_trans, logreg)

In [56]:
# cross-validate the entire process
# thus, preprocessing occurs within each fold of cross-validation
cross_val_score(pipe, X, y, cv=5, scoring='accuracy').mean()

0.7727924839713071

## Step 6: Make predictions on "new" data

In [57]:
X_new = X.sample(5, random_state=99)
X_new

Pclass     Sex Embarked
599       1    male        C
512       1    male        S
273       1    male        C
215       1  female        C
790       3    male        Q

In [58]:
pipe.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['Sex', 'Embarked'])])),
                ('logisticregression', LogisticRegression())])

In [59]:
pipe.predict(X_new)

array([1, 0, 1, 1, 0], dtype=int64)

## Recap

In [2]:
import pandas as pd
from sklearn.compose import make_column_transformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import cross_val_score

In [3]:
path_0 = "Scikit_Learn\\data\\titanic_train.csv"
df = pd.read_csv(path_0)
df = df.loc[df.Embarked.notna(), ['Survived', 'Pclass', 'Sex', 'Embarked']]
X = df.drop('Survived', axis='columns')
y = df.Survived

In [64]:
column_trans = make_column_transformer(
    (OneHotEncoder(), ['Sex', 'Embarked']),
    remainder='passthrough')
logreg = LogisticRegression(solver='lbfgs')

In [65]:
pipe = make_pipeline(column_trans, logreg)

In [66]:
cross_val_score(pipe, X, y, cv=5, scoring='accuracy').mean()

0.7727924839713071

In [67]:
X_new = X.sample(5, random_state=99)

In [68]:
pipe.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(),
                                                  ['Sex', 'Embarked'])])),
                ('logisticregression', LogisticRegression())])

In [69]:
pipe.predict(X_new)

array([1, 0, 1, 1, 0], dtype=int64)